apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backing-store
  namespace: codex
  labels:
    app.kubernetes.io/part-of: codex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 10Gi
