/**
 * Plugin Registry Service
 *
 * Registers plugins with the backend on app startup.
 * Plugin manifest is fetched from the backend API (/api/v1/plugins/manifest),
 * which reads from the plugins.json generated by the plugin build script.
 */

import api from "./api"

/**
 * Plugin registration request
 */
export interface PluginRegistration {
  id: string
  name: string
  version: string
  type: "view" | "theme" | "integration"
  manifest: Record<string, unknown>
}

/**
 * Plugin registration response
 */
export interface PluginRegistrationResponse {
  id: string
  name: string
  version: string
  type: string
  registered: boolean
  message: string
}

/**
 * Batch registration response
 */
export interface BatchRegistrationResponse {
  registered: number
  updated: number
  failed: number
  results: PluginRegistrationResponse[]
}

/**
 * Plugins manifest structure (generated by build script, served by backend)
 */
interface PluginsManifest {
  version: string
  buildTime: string
  plugins: PluginRegistration[]
}

// Cache for loaded plugins
let pluginsCache: PluginRegistration[] | null = null
let pluginsLoadPromise: Promise<PluginRegistration[]> | null = null

/**
 * Load plugins from the backend manifest endpoint.
 */
async function loadPlugins(): Promise<PluginRegistration[]> {
  if (pluginsCache) {
    return pluginsCache
  }

  if (pluginsLoadPromise) {
    return pluginsLoadPromise
  }

  pluginsLoadPromise = (async () => {
    try {
      const response = await fetch("/api/v1/plugins/manifest")
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`)
      }
      const manifest: PluginsManifest = await response.json()
      pluginsCache = manifest.plugins
      console.log(`Loaded ${manifest.plugins.length} plugins from backend (built ${manifest.buildTime})`)
      return pluginsCache
    } catch (err) {
      console.warn("Plugin manifest not available from backend.", err)
      return []
    }
  })()

  return pluginsLoadPromise
}

class PluginRegistryService {
  private registered = false
  private registrationPromise: Promise<BatchRegistrationResponse> | null = null

  /**
   * Register all plugins with the backend.
   * This should be called during app initialization.
   * Safe to call multiple times - will only register once.
   */
  async registerPlugins(): Promise<BatchRegistrationResponse> {
    if (this.registered) {
      return {
        registered: 0,
        updated: 0,
        failed: 0,
        results: [],
      }
    }

    if (this.registrationPromise) {
      return this.registrationPromise
    }

    this.registrationPromise = this._doRegister()

    try {
      const result = await this.registrationPromise
      this.registered = true
      return result
    } finally {
      this.registrationPromise = null
    }
  }

  private async _doRegister(): Promise<BatchRegistrationResponse> {
    try {
      const plugins = await loadPlugins()

      if (plugins.length === 0) {
        console.warn("No plugins found to register")
        return {
          registered: 0,
          updated: 0,
          failed: 0,
          results: [],
        }
      }

      const response = await api.post<BatchRegistrationResponse>(
        "/api/v1/plugins/register-batch",
        { plugins }
      )
      console.log(
        `Plugins registered: ${response.data.registered} new, ${response.data.updated} updated, ${response.data.failed} failed`
      )
      return response.data
    } catch (error) {
      console.error("Failed to register plugins with backend:", error)
      const plugins = pluginsCache || []
      // Return empty result on failure - plugins will work in frontend-only mode
      return {
        registered: 0,
        updated: 0,
        failed: plugins.length,
        results: [],
      }
    }
  }

  /**
   * Get the list of plugins.
   * Note: This is async since plugins are loaded from the backend
   */
  async getPlugins(): Promise<PluginRegistration[]> {
    const plugins = await loadPlugins()
    return [...plugins]
  }

  /**
   * Get the list of plugins (sync version).
   * Returns cached plugins or empty array if not yet loaded.
   * @deprecated Use getPlugins() instead for guaranteed results
   */
  getKnownPlugins(): PluginRegistration[] {
    return pluginsCache ? [...pluginsCache] : []
  }

  /**
   * Get plugins by type.
   * Note: This is async since plugins are loaded from the backend
   */
  async getPluginsByType(type: "view" | "theme" | "integration"): Promise<PluginRegistration[]> {
    const plugins = await loadPlugins()
    return plugins.filter((p) => p.type === type)
  }

  /**
   * Check if a plugin is known by the frontend.
   * Note: This is async since plugins are loaded from the backend
   */
  async isPluginKnown(pluginId: string): Promise<boolean> {
    const plugins = await loadPlugins()
    return plugins.some((p) => p.id === pluginId)
  }
}

// Export singleton instance
export const pluginRegistry = new PluginRegistryService()
