"""API routes for plugin manifest and asset serving.

This module serves plugin metadata (manifest) and compiled assets (JS, CSS,
stylesheets) to the frontend. The frontend uses these to discover available
themes, blocks, and integrations.
"""

import json
import logging
import os
import re
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse

logger = logging.getLogger(__name__)
router = APIRouter()


# --- Plugin Assets routes ---
# These endpoints serve plugin files (manifest, JS, CSS, stylesheets) to the frontend.

# Allowed file extensions for serving plugin assets
_ALLOWED_EXTENSIONS = {".js", ".css", ".map", ".json", ".svg", ".png", ".jpg", ".woff", ".woff2"}

# Content type mapping
_CONTENT_TYPES = {
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".map": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
}


def _get_plugins_dir(request: Request) -> Path:
    """Get the plugins directory from app state."""
    plugins_dir = getattr(request.app.state, "plugins_dir", None)
    if not plugins_dir:
        raise HTTPException(status_code=503, detail="Plugins directory not configured")
    return Path(plugins_dir)


@router.get("/manifest")
async def get_plugins_manifest(request: Request):
    """Serve the unified plugins manifest.

    Returns the plugins.json generated by the build script, which contains
    all plugin metadata and component file mappings. The frontend uses this
    to discover available plugins, themes, views, and blocks.
    """
    plugins_dir = _get_plugins_dir(request)
    manifest_path = plugins_dir / "plugins.json"

    if not manifest_path.exists():
        return {"version": "1.0.0", "buildTime": "", "plugins": []}

    try:
        with open(manifest_path) as f:
            return json.load(f)
    except Exception as e:
        logger.error(f"Failed to read plugins manifest: {e}")
        raise HTTPException(status_code=500, detail="Failed to read plugin manifest")


@router.get("/assets/{file_path:path}")
async def serve_plugin_asset(file_path: str, request: Request):
    """Serve a plugin asset file (JS, CSS, stylesheets, images).

    Supports two path formats:

    1. Versioned: ``{plugin_id}/{version}/{file}``
       Used for compiled components.

    2. Direct: ``{plugin_id}/{relative_path}``
       Used for theme stylesheets and other non-versioned assets
       (e.g. ``cream/styles/main.css``).
    """
    plugins_dir = _get_plugins_dir(request)

    # Check file extension first (cheap, avoids filesystem work)
    ext = os.path.splitext(file_path)[1].lower()
    if ext not in _ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=403, detail=f"File type not allowed: {ext}")

    # Parse the path to detect versioned format: {plugin_id}/{version}/{file}
    parts = file_path.split("/", 2)
    resolved: Path | None = None

    if len(parts) >= 3 and re.match(r"^\d+\.\d+\.\d+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$", parts[1]):
        # Versioned path – resolve to {plugin_id}/dist/{file}
        plugin_id, _version, remainder = parts
        candidate = (plugins_dir / plugin_id / "dist" / remainder).resolve()
        plugins_resolved = plugins_dir.resolve()
        if str(candidate).startswith(str(plugins_resolved)) and candidate.is_file():
            resolved = candidate

    if resolved is None:
        # Direct path – serve relative to plugins_dir
        try:
            resolved = (plugins_dir / file_path).resolve()
            if not str(resolved).startswith(str(plugins_dir.resolve())):
                raise HTTPException(status_code=403, detail="Access denied")
        except (ValueError, OSError):
            raise HTTPException(status_code=400, detail="Invalid file path")

    if not resolved.is_file():
        raise HTTPException(status_code=404, detail="Asset not found")

    content_type = _CONTENT_TYPES.get(ext, "application/octet-stream")
    return FileResponse(resolved, media_type=content_type)
