apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codex

resources:
  - ../../base

images:
  - name: ghcr.io/OWNER/codex-backend
    newName: ghcr.io/OWNER/codex-backend # CI replaces OWNER
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: codex-ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: codex.melloy.life
      - op: replace
        path: /spec/rules/0/host
        value: codex.melloy.life
