apiVersion: v1
kind: Secret
metadata:
    name: codex-secrets
    namespace: codex
    labels:
        app.kubernetes.io/part-of: codex
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:lvfI+R6ZoNqWSj8kqtqHDuvekWIVYost0EfK+BTqfgMpjSm5i3Q2uLLW6T9dUSM8m+jcPA+HpSXPhHLAIWfD7Q==,iv:omGOqURqF5PubIuUu11/utSgg1XjNxqoVUm+1jVAEcI=,tag:+GTFkYk5KfwohfBwt5xfYg==,type:str]
    OPENGRAPH_IO_API_KEY: ENC[AES256_GCM,data:tz9leA4nn6MJxjzEtzhan7yxfJIoB4FTJ4KGvhBFCksyHPiI,iv:NtIo2uOSKWvuoBmkdMtbxixxMJuBwSgAcoCzzLbv26w=,tag:vxzJIEQhSw2zqaMR3SGxiw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:DSf447A9uLFnXxHZld3TEAfXEKmg5PDxFn6o36N7Ioi70RNcs52Va3ctt9+QJaR5mn/OfV3s8tn5lm8fOSofHeWuS6xNW3ne,iv:TshF9QIKHajhb59UEeDqoS3G+PX51S3PuBX0hj3V7D8=,tag:prdFgW4OHMgCp9Cruantqg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:f0bSc134OQ4t6LXy/Cdo1Z83ZZDb6s0IFUaPijERqSQMeoY=,iv:SSsf0DrQlWCJRrxnwAFjHFzmEH06uXDo2CZ3A6VWNOU=,tag:t/7t17sWndDW2d8jolinOw==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:T5CF1T/PriY5WEEcUIkED/7qNJspEaapZbLgx8QffN2/wI0J8MVDkk1F0WC3Bg==,iv:g2Hji3bPHeQgU+fQ416Hc1KqZxZFqhXOGc0qIMIEcSk=,tag:YGQnCUrt/8kwdAZQ7TTcJg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:ImZ7HxmpBTfubbWXlMcBdK5ptRKgGyIIBld/SGVokf9B4JNbJ2CAvg6J810gsveB4xOLSbnEe+9QjnHzUJHn7GgJv4OhFmzwL0bclG27JlmWYF01ji3gksCeAX869CO2QZl7XewsT8i19oAV4vyJB00H88hOOyL4SZc/bcHwOa+Sebv+klHalgi6IrTtYIUw2tse04al7s2eajg1d5IzYuRdRMo7s2E=,iv:tkJt8+Q1yjkbuA8bye5omV/czkaENa7Sb3+2jLpDHDA=,tag:njJO64pR938Ej4yam+yUdA==,type:str]
sops:
    age:
        - recipient: age1k58frs2xulq70rvttn50rkegf9udexdz4ejfmj772ltqqelm03ssendps6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSmlWR3RNTmo3U0RCbW1N
            VjVwa1hOcW0rcHFIR0VGNUlIYkZpeHdTVVF3CmFId05xMG1sUDB5YVdWNm9wMGxS
            Y2xWZFZSRFRiOWhkc2pETUhPUVFIQ1kKLS0tIDhPdit6dHNlWE5KWWRCVTh5Z1FR
            YzNPb0V6ZVlmdlZ1QnAzU1ZpdW4rbjQKQOPHHCZhWehPpckBQmTWjVkPJFgSF26A
            Y8uQgD+FZ3ScJqLYvOfs+21qXFquTnmkozbb7oIKGjd9joKkJiKRWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T16:59:45Z"
    mac: ENC[AES256_GCM,data:wR4n6zL4Gm33pFJXzQqp2pVv5/AGS4G9Zw4dljM3gUUOdOPtL3m7LcBZS/JjcflFVVlTRnlwJjPs6P5E56tOiHfQMegJhXSX7eW/K/i16eglnwbsAYbBTYL4HbuINp1kmmPLj7SyaC9XcrC+UC9EO51yga0lI/qa+k8ffVxRd1M=,iv:8Z31yKkitzbp1U5gxu0+YW+FC4kiDtjSd+l0BNoSnFI=,tag:f+VBBueQuPnQclxmcDuNhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
