apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codex-data
  namespace: codex
  labels:
    app.kubernetes.io/part-of: codex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 8Gi
