apiVersion: v1
kind: Secret
metadata:
    name: codex-secrets
    namespace: codex
    labels:
        app.kubernetes.io/part-of: codex
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:lvfI+R6ZoNqWSj8kqtqHDuvekWIVYost0EfK+BTqfgMpjSm5i3Q2uLLW6T9dUSM8m+jcPA+HpSXPhHLAIWfD7Q==,iv:omGOqURqF5PubIuUu11/utSgg1XjNxqoVUm+1jVAEcI=,tag:+GTFkYk5KfwohfBwt5xfYg==,type:str]
    OPENGRAPH_IO_API_KEY: ENC[AES256_GCM,data:tz9leA4nn6MJxjzEtzhan7yxfJIoB4FTJ4KGvhBFCksyHPiI,iv:NtIo2uOSKWvuoBmkdMtbxixxMJuBwSgAcoCzzLbv26w=,tag:vxzJIEQhSw2zqaMR3SGxiw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:DSf447A9uLFnXxHZld3TEAfXEKmg5PDxFn6o36N7Ioi70RNcs52Va3ctt9+QJaR5mn/OfV3s8tn5lm8fOSofHeWuS6xNW3ne,iv:TshF9QIKHajhb59UEeDqoS3G+PX51S3PuBX0hj3V7D8=,tag:prdFgW4OHMgCp9Cruantqg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:f0bSc134OQ4t6LXy/Cdo1Z83ZZDb6s0IFUaPijERqSQMeoY=,iv:SSsf0DrQlWCJRrxnwAFjHFzmEH06uXDo2CZ3A6VWNOU=,tag:t/7t17sWndDW2d8jolinOw==,type:str]
sops:
    age:
        - recipient: age1k58frs2xulq70rvttn50rkegf9udexdz4ejfmj772ltqqelm03ssendps6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSmlWR3RNTmo3U0RCbW1N
            VjVwa1hOcW0rcHFIR0VGNUlIYkZpeHdTVVF3CmFId05xMG1sUDB5YVdWNm9wMGxS
            Y2xWZFZSRFRiOWhkc2pETUhPUVFIQ1kKLS0tIDhPdit6dHNlWE5KWWRCVTh5Z1FR
            YzNPb0V6ZVlmdlZ1QnAzU1ZpdW4rbjQKQOPHHCZhWehPpckBQmTWjVkPJFgSF26A
            Y8uQgD+FZ3ScJqLYvOfs+21qXFquTnmkozbb7oIKGjd9joKkJiKRWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T16:59:34Z"
    mac: ENC[AES256_GCM,data:KwQ2EUFaBWLJN4pVuX75RzZhEitjrpWR2w4anK+M+IgxILHnF3ORChd/pKDJrCtkHGI+nuII/RjoelY43f/QUJpbZ9ezKtnPgEi1ts50oUuQX/Is28SGMJYixxFC9BiWfW7HFdgMeX7T9pBCRzhOClqVArKKbS+UTgqbz8fCe0g=,iv:1GrCi8ny2ewyKifcxC0tuzb9HojzsAWivOUsOoqVNaQ=,tag:he7FadFA/ul1Y11lpMgXDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
