apiVersion: v1
kind: Secret
metadata:
    name: codex-secrets
    namespace: codex
    labels:
        app.kubernetes.io/part-of: codex
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:lvfI+R6ZoNqWSj8kqtqHDuvekWIVYost0EfK+BTqfgMpjSm5i3Q2uLLW6T9dUSM8m+jcPA+HpSXPhHLAIWfD7Q==,iv:omGOqURqF5PubIuUu11/utSgg1XjNxqoVUm+1jVAEcI=,tag:+GTFkYk5KfwohfBwt5xfYg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:miC0G8o=,iv:wFEAb+WOnPDlXtyumTz2oF+sMxUobdANbKGgunwZ1vk=,tag:OQ+iKgozvrBDFewn9sNZPg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/mkEEIJaCl39W4VoPa6eoUGKl2vUTeqA7wXOrAWT1Bo=,iv:BaeOlLy/x/3I3xJCMwVGEbZ6R2XAN02rdRbKxxRY2yU=,tag:hV/GDeQ1YQ759jxufcXzDg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:mr+BAOOSR45YcT9EEihdHPluuNzkS5LSnX3q2KiyiH1EVfQsGsRHbZiUBFnCEnUgBRHqnoBGpLLA7lCR3iv5ADlrDGKO0ec=,iv:BsE+VI/h4RwlIsDqj9Zlf+Ddpg6NEuSTZqoNKsPYPHo=,tag:jxuPzi8Bb2hTJHpRfS05Qw==,type:str]
    OPENGRAPH_IO_API_KEY: ENC[AES256_GCM,data:tz9leA4nn6MJxjzEtzhan7yxfJIoB4FTJ4KGvhBFCksyHPiI,iv:NtIo2uOSKWvuoBmkdMtbxixxMJuBwSgAcoCzzLbv26w=,tag:vxzJIEQhSw2zqaMR3SGxiw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:DSf447A9uLFnXxHZld3TEAfXEKmg5PDxFn6o36N7Ioi70RNcs52Va3ctt9+QJaR5mn/OfV3s8tn5lm8fOSofHeWuS6xNW3ne,iv:TshF9QIKHajhb59UEeDqoS3G+PX51S3PuBX0hj3V7D8=,tag:prdFgW4OHMgCp9Cruantqg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:f0bSc134OQ4t6LXy/Cdo1Z83ZZDb6s0IFUaPijERqSQMeoY=,iv:SSsf0DrQlWCJRrxnwAFjHFzmEH06uXDo2CZ3A6VWNOU=,tag:t/7t17sWndDW2d8jolinOw==,type:str]
sops:
    age:
        - recipient: age1k58frs2xulq70rvttn50rkegf9udexdz4ejfmj772ltqqelm03ssendps6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSmlWR3RNTmo3U0RCbW1N
            VjVwa1hOcW0rcHFIR0VGNUlIYkZpeHdTVVF3CmFId05xMG1sUDB5YVdWNm9wMGxS
            Y2xWZFZSRFRiOWhkc2pETUhPUVFIQ1kKLS0tIDhPdit6dHNlWE5KWWRCVTh5Z1FR
            YzNPb0V6ZVlmdlZ1QnAzU1ZpdW4rbjQKQOPHHCZhWehPpckBQmTWjVkPJFgSF26A
            Y8uQgD+FZ3ScJqLYvOfs+21qXFquTnmkozbb7oIKGjd9joKkJiKRWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T21:15:53Z"
    mac: ENC[AES256_GCM,data:u3SseNX8CGebn+Fc6ev2wfM4OTSA8I2rD94OiJ6RWGTB45rwCwnewjtLuEGHYvXCGMZ/xBUxbcU/Xk1y13L7+S0Z5NjhSQh2F3ZdJV1ieyVxU8scwxDAVCP+XgpD2qbuQlH9tmuppg28yyNOUrI7AiIl9sNN2YmRvlG4u/q1Ogs=,iv:9Ojwcfu7TMDxCwNcesl3OXWejsNiQcxk4MIacbZabjM=,tag:vp4awzHhdRyKrFxcNArlCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
